services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5435:5432
    volumes:
      - postgres_db_data_container:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8079:8080

volumes:
  postgres_db_data_container:
