services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: KlVXqgEJKVIzLaE4fmI=
    ports:
      - 5432:5432
    volumes:
      - postgres_db_data_container:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_db_data_container:
