name: Build and Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          # Build each service and save as a tar file
          for service in auth-service ticket-service notification-service frontend-next; do
            echo "Building $service..."
            docker build -t buet-hackathon-$service:latest ./$service
            docker save buet-hackathon-$service:latest -o $service.tar
          done

      - name: Transfer Docker images to VPS
        env:
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
          VPS_USER: ${{ secrets.VPS_USER }}
          SERVER_IP: ${{ secrets.VPS_HOST}}
        run: |
          # Install sshpass
          sudo apt-get install -y sshpass

          # Copy the tar files to the server using sshpass
          for service in auth-service ticket-service notification-service frontend-next; do
            echo "Transferring $service.tar to VPS..."
            sshpass -p "$VPS_PASSWORD" scp -o StrictHostKeyChecking=no $service.tar $VPS_USER@$SERVER_IP:/app/images/
          done

      - name: Deploy on VPS
        env:
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
          VPS_USER: ${{ secrets.VPS_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          # SSH into the server and load the images and run the containers using sshpass
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$SERVER_IP << 'EOF'
            for service in auth-service ticket-service notification-service frontend-next; do
              echo "Loading $service image..."
              docker load -i /app/images/$service.tar
              echo "Running $service container..."
              docker run -d --name $service buet-hackathon-$service:latest
            done
          EOF
